behaviors:
  Car:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.01
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 5
      vis_encode_type: nature_cnn
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: True
      rnd:
        gamma: 0.99
        strength: 0.1
        network_settings:
          hidden_units: 64
          num_layers: 3
          normalize: True
        learning_rate: 0.0001
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 100000000
    time_horizon: 512
    summary_freq: 50000
    threaded: true
    self_play: null
    behavioral_cloning: null
